blog/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from blog import db, login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(100))
    email = db.Column(db.String(255),unique = True, index = True, nullable=False)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))

    blogs = db.relationship('Blog',backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment',backref = 'user', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attritube')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    content = db.Column(db.String(10000))
    category = db.Column(db.String(), nullable = False)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    comments = db.relationship('Comment',backref =  'blogit',lazy = "dynamic")

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls,category):
        blogs = Blog.query.filter_by(category = category).all()
        return blogs

    @classmethod
    def get_blog(cls,id):
        blog = Blog.query.filter_by(id = id).first()

        return blog

    def __repr__(self):
        return f'Blog {self.title}'

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(1000))
    name = db.Column(db.String)
    blog = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,blog):
        comments = Comment.query.filter_by(blogit = blog).all()
        return comments

    @classmethod
    def delete_comment(cls,id):
        comment = Comment.query.filter_by(id=id).first()
        db.session.delete(comment)
        db.session.commit()

    def __repr__(self):
        return f'Comment{self.comment}'


class Subscriber(db.Model):
    __tablename__ = 'subscribers'

    id = db.Column(db.Integer,primary_key = True)
    subscriber_name = db.Column(db.String(50))
    subscriber_email = db.Column(db.String(255), unique = True)

class Quotes:
  def __init__ (self,author,quote):
    self.author = author
    self.quote = quote
    

blog/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required, Email, DataRequired, Length
from flask_wtf.file import FileAllowed, FileField
from flask_login import current_user

class UpdateProfile(FlaskForm):
    username = StringField('Username')
    email = StringField('Email', Email)
    bio = TextAreaField('Tell us something about you.',validators = [Required()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):
    title = StringField('Blog Title',validators=[Required()])
    blog_body = TextAreaField('Write Blog Content',validators=[Required()])
    blog_category = SelectField('Blog Category',choices=[('Sports-Blog','Sports'),('Travel-Blog','Travel'),('Fitness-Blog','Fitness'),('Fashion-Blog','Fashion'),('Food-Blog','Food'),('Political-Blog','Politics')],validators=[Required()])
    submit = SubmitField('Submit Blog')

class CommentForm(FlaskForm):
    name = StringField('Enter Your Name',validators=[Required()])
    comment = TextAreaField('Comments', validators=[Required()])
    submit = SubmitField('Submit Comment')

class SubscribeForm(FlaskForm):
    subscriber_name = StringField('Enter your Full Name',validators=[Required()])
    subscriber_email = StringField('Enter your Email',validators=[Required(),Email()])
    submit = SubmitField('Subscribe')

blog/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
# from flask_uploads import UploadSet,configure_uploads,IMAGES


bootstrap = Bootstrap()
db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'info'

def create_app(config_name):

    app = Flask(__name__)
    app.debug = True

    # App Configurations
    app.config.from_object(config_options[config_name])

    # Initialize flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # Register main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Register auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Register errors blueprint
    from .errors import errors as errors_blueprint
    app.register_blueprint(errors_blueprint)

    return app

blog/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

blog/main/views.py
from flask import render_template, request, redirect, url_for, flash, abort
from . import main
from blog.models import Role, Blog, Comment, Subscriber, User
from .forms import UpdateProfile, CommentForm, BlogForm, SubscribeForm
from flask_login import login_required, current_user
from wtforms import Form
from blog import db
from blog.requests import get_Quotes


@main.route("/")
@main.route("/home")
def home():
    quotes=get_Quotes()
    print(quotes)
    sports = Blog.get_blogs('Sports-Blog')
    travel = Blog.get_blogs('Travel-Blog')
    fitness = Blog.get_blogs('Fitness-Blog')
    fashion = Blog.get_blogs('Fashion-Blog')
    food = Blog.get_blogs('Food-Blog')
    politics = Blog.get_blogs('Political-Blog')

    return render_template('home.html', sports = sports, travel = travel, fitness = fitness, fashion = fashion, food = food, quotes = quotes)
@main.route('/user/<username>')
def profile(username):
    user = User
    user = User.query.filter_by(username = username).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))
    return render_template('profile/profile.html', title='Account',
                            form=form)

@main.route('/new-blog', methods = ['GET','POST'])
@login_required
def new_blog():
    blog_form = BlogForm()
    if blog_form.validate_on_submit():
        title = blog_form.title.data
        blog = blog_form.blog_body.data
        category = blog_form.blog_category.data

        new_blog = Blog(title = title, content = blog, category = category,user = current_user)
        new_blog.save_blog()

        return redirect(url_for('main.home'))

    title = 'New Blog'
    return render_template('new_blog.html', title = title, blog_form = blog_form)

@main.route('/blog/<int:id>', methods = ["GET","POST"])
def blog(id):
    blog = Blog.get_blog(id)
    posted_date = blog.posted.strftime('%b %d, %Y')

    comment_form = CommentForm()
    if comment_form.validate_on_submit():

        name = comment_form.name.data
        comment = comment_form.comment.data

        new_comment = Comment(name = name, comment = comment, blogit = blog)
        new_comment.save_comment()

        return redirect(url_for('main.blog',id=id))
    
    comments = Comment.get_comments(blog)
    return render_template('blogs.html', blog = blog, comment_form = comment_form, comments = comments, date = posted_date)

@main.route('/blog/<int:id>/update', methods = ['GET','POST'])
@login_required
def update_blog(id):
    blog = Blog.get_blog(id)
    form = BlogForm()
    if form.validate_on_submit():
        blog.title = form.title.data
        blog.content = form.blog_body.data
        blog.category = form.blog_category.data
        db.session.commit()
        return redirect(url_for('main.blog', id = id))
    elif request.method == 'GET':
        form.title.data = blog.title
        form.blog_body.data = blog.content
        form.blog_category.data = blog.category
    return render_template('new_blog.html', blog_form = form, id=id)

@main.route('/blog/delete/<int:id>', methods = ['GET', 'POST'])
@login_required
def delete_blog(id):
    blog = Blog.get_blog(id)
    db.session.delete(blog)
    db.session.commit()

    flash('Your blog has been deleted')
    return redirect(url_for('main.home'))
    
    return render_template('blogs.html', id=id, blog = blog)

@main.route('/blog/comment/delete/<int:id>', methods = ['GET', 'POST'])
@login_required
def delete_comment(id): 
    comment = Comment.query.filter_by(id=id).first()
    blog_id = comment.blog
    Comment.delete_comment(id)

    flash('Comment has been deleted')
    return redirect(url_for('main.blog',id=blog_id))

@main.route('/blogs/sports')
def sports():
    blogs = Blog.get_blogs('Sports-Blog')

    return render_template('sports.html',blogs = blogs)

@main.route('/blogs/travel')
def travel():
    blogs = Blog.get_blogs('Travel-Blog')

    return render_template('travel.html',blogs = blogs)


@main.route('/blogs/fitness')
def fitness():
    blogs = Blog.get_blogs('Fitness-Blog')

    return render_template('fitness.html',blogs = blogs)

@main.route('/blogs/fashion')
def fashion():
    blogs = Blog.get_blogs('Fashion-Blog')

    return render_template('fashion.html',blogs = blogs)

@main.route('/blogs/food')
def food():
    blogs = Blog.get_blogs('Food-Blog')

    return render_template('food.html',blogs = blogs)

@main.route('/blogs/politics')
def politics():
    blogs = Blog.get_blogs('Political-Blog')

    return render_template('politics.html',blogs = blogs)

@main.route('/blogs/latest', methods = ['GET','POST'])
def latest_blogs():
    blogs = Blog.query.order_by(Blog.posted.desc()).all()

    return render_template('latest_blog.html',blogs = blogs)

@main.route('/subscription',methods=['GET','POST'])
def subscription():
    subscription_form = SubscribeForm()

    if subscription_form.validate_on_submit():
        new_subscriber = Subscriber(subscriber_name=subscription_form.subscriber_name.data,subscriber_email=subscription_form.subscriber_email.data)

        db.session.add(new_subscriber)
        db.session.commit()

        return redirect(url_for('main.home'))    

    return render_template('subscription.html',subscription_form = subscription_form)

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="../static/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
  <nav class="mb-1 navbar navbar-expand-lg navbar-dark secondary-color navsize" style="background-color: blue;margin-top: -80px;">
    <a class="navbar-brand" href="/">Blog your Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.latest_blogs')}}" style="color: white;"> Latest Blogs </a>
          </li>

          {% if current_user.is_authenticated %}
           <li class="nav-item"><a class="nav-link" href="{{url_for('main.new_blog')}}" style="color: white;"> Create Blog </a></li>
          {% endif %}
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons" style="color: white;">
          {% if current_user.is_authenticated %}
          <li style="font-weight: bold;font-style: italic;padding-left:10px;padding-right:10px;">| {{current_user.username}} |</li>
          <li><a href="{{url_for('auth.logout')}}" style="color: white;"> Log out </a></li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="{{url_for('auth.register')}}">
            <i class="fas fa-user"> | Register |</i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="{{url_for('auth.login')}}">
              <i class="fas fa-sign-out-alt"> | Log in |</i>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <!-- Navbar -->
    <main role="main" class="">
      <div class="row" style="font-family: 'Oswald', sans-serif;">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blogs.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content%}
<div class="container-fluid" style="font-family: 'Oswald', sans-serif;">
    <div class="card text-center" style="max-width: 95rem;">
        <div class="card-header">
            <h3>| Full Blog Post |</h3>
        </div>
        <div class="card-body">
            <h4><strong>{{blog.title}}</strong></h4>
            <p style="font-family: 'Oswald', sans-serif;">{{blog.content}}</p>
            {% if current_user.is_authenticated %}
            <a href="{{url_for('main.update_blog',id=blog.id)}}" class="btn btn-primary">| Update Blog |</a>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteBlogModal">| Delete
                Blog |</button>
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            Created on <strong>{{date}}</strong> by <strong>{{blog.user.username}}</strong>
        </div>
    </div>
    <div class="cmm">
        <h5><strong>Leave Your Comments Below</strong></h5>
        {{wtf.quick_form(comment_form)}}


    </div>

    <div class="modal fade right" id="deleteBlogModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-side modal-top-right" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title w-100" id="myModalLabel">Delete</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <form action="{{url_for('main.delete_blog',id=blog.id)}}" method="POST">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        {{macro.displayComments(comments)}}
    </div>
</div>
{% endblock%}

blog/templates/fashion.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<!-- Jumbotron -->
<div class="jumbotron text-center mdb-color lighten-2 white-text mx-2 mb-5">

        <!-- Title -->
        <h2 class="card-title h2">Latest Fashion Trends Blogs</h2>      
      
        <hr class="my-4 rgba-white-light">   
      
      </div>
      <!-- Jumbotron -->
      <div class="row">
          <div class="col-md-5"></div>
          <div class="col-md-6">
         {% if current_user.is_authenticated %}
          <h4 class="text-center bg-light mb-3 btn "><a href="{{url_for('main.new_blog')}}">Create Your Blog</a></h4>
         {% endif%}
        </div>
         
      </div>
<div class="container-fluid" style="font-family: 'Oswald', sans-serif;">
  <div class="row">
    {{macro.displayBlogs(blogs)}}
  </div>
</div>
{%endblock%}

blog/templates/fitness.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}

<div class="jumbotron text-center mdb-color lighten-2 white-text mx-2 mb-5">

        
        <h2 class="card-title h2">Improve your wellbeing with fitness tips</h2>      
      
        <hr class="my-4 rgba-white-light">   
      
      </div>
      
      <div class="row">
            <div class="col-md-5"></div>
            <div class="col-md-6">
           {% if current_user.is_authenticated %}
            <h4 class="text-center btn bg-light mb-3"><a href="{{url_for('main.new_blog')}}">Create Your Blog</a></h4>
           {% endif%}
          </div>
           
        </div>
<div class="container-fluid" style="font-family: 'Oswald', sans-serif;">
  <div class="row">
    {{macro.displayBlogs(blogs)}}
  </div>
</div>
{%endblock%}

blog/templates/food.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}

<div class="jumbotron text-center mdb-color lighten-2 white-text mx-2 mb-5">

        
        <h2 class="card-title h2">Latest Food Blogs</h2>      
      
        <hr class="my-4 rgba-white-light">   
      
      </div>
      
      <div class="row">
          <div class="col-md-5"></div>
          <div class="col-md-6">
         {% if current_user.is_authenticated %}
          <h4 class="text-center btn bg-light mb-3"><a href="{{url_for('main.new_blog')}}">Create Your Blog</a></h4>
         {% endif%}
        </div>
         
      </div>
<div class="container-fluid" style="font-family: 'Oswald', sans-serif;">
  <div class="row" style="font-family: 'Oswald', sans-serif;">
    {{macro.displayBlogs(blogs)}}
  </div>
</div>
{%endblock%}

blog/templates/latest_blog.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}
<div class="container-fluid" style="font-family: 'Oswald', sans-serif;">
    <div class="row" style="font-family: 'Oswald', sans-serif;">
            {{macro.displayBlogs(blogs)}}
    </div>
</div>

{% endblock %}

blog/templates/macros.html
{% macro displayBlogs(my_blog_list) %}
    {% for blogs in my_blog_list %}
    
    <div class="card border-info mb-3 spacing" style="min-width: 20rem;max-width: 20rem;">
            <div class="card-body">
              <h4 class="card-title" style="font-family: 'Oswald', sans-serif;"><strong>{{blogs.title}}</strong></h4>
              <p class="card-text" style="font-family: 'Oswald', sans-serif;">{{blogs.content| truncate(100)}}</p>
              <p style="font-family: 'Oswald', sans-serif;">Posted By: <strong>{{blogs.user.username}}</strong></p>
              <p>Date posted {{blogs.posted.strftime('%Y-%m-%d')}}</p>
              <a href="/blog/{{blogs.id}}" class="card-link btn btn-success float-right">Full Blog</a>
            </div>
          </div>
       
    {% endfor %}
{% endmacro%}

{% macro displayComments(my_comments) %}
   {% for comments in my_comments %}
   <div class="card border-dark comment" style="min-width: 20rem;max-width: 20rem;">
      <div class="card-header">Comments</div>
      <div class="card-body text-dark">
        <h5 class="card-title" style="font-family: 'Oswald', sans-serif;"><strong>{{comments.name}}</strong></h5>
        <p class="card-text" style="font-family: 'Oswald', sans-serif;">{{comments.comment}}</p>        
      </div>
      
      <div class="card-footer bg-transparent">
        <div >
            <button class="btn btn-danger float-right" data-toggle="modal" data-target="#deleteModalRight">Delete</button> 
        </div>
      </div>
    
    </div>
<div class="modal fade" id="deleteModalRight" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
aria-hidden="true">

<div class="modal-dialog modal-sm modal-top" role="document">


  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title w-100" id="myModalLabel">Delete Comment</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
        Confirm you want to delete this comment
    </div>
    <div class="modal-footer justify-content-center">
      <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      <form action="{{url_for('main.delete_comment',id=comments.id)}}" method="POST">
          <button type="submit" class="btn btn-danger">Delete</button>
      </form>      
    </div>
  </div>
</div>
</div>
   {% endfor %}
{% endmacro %}

blog/templates/navbar.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark secondary-color navsize" style="height: 60px;">
    <a class="navbar-brand" href="/">Blogger Inc.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.latest_blogs')}}">| Latest Blogs |</a>
          </li>

          {% if current_user.is_authenticated %}
           <li class="nav-item"><a class="nav-link" href="{{url_for('main.new_blog')}}">| Create Blog |</a></li>
          {% endif %}
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">| Profile |</a></li>
          <li style="font-weight: bold;font-style: italic;padding-left:10px;padding-right:10px;">| {{current_user.username}} |</li>
          <li><a href="{{url_for('auth.logout')}}">| Log out |</a></li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="{{url_for('auth.register')}}">
            <i class="fas fa-user"> | Register |</i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="{{url_for('auth.login')}}">
              <i class="fas fa-sign-out-alt"> | Log in |</i>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <!-- Navbar -->

blog/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="margin-top: 50px">
        <div class="col-md-2"></div>
        <div class="col-md-8" style="font-family: 'Oswald', sans-serif;">
            {{ wtf.quick_form(blog_form) }}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

blog/templates/politics.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="jumbotron text-center mdb-color lighten-2 white-text mx-2 mb-5">

      
        <h2 class="card-title h2" style="font-family: 'Oswald', sans-serif;">Only the best and most trending Political blogs</h2>      
      
        <hr class="my-4 rgba-white-light">   
      
      </div>
      
      <div class="row">
          <div class="col-md-5"></div>
          <div class="col-md-6">
         {% if current_user.is_authenticated %}
          <h4 class="text-center btn bg-light mb-3"><a href="{{url_for('main.new_blog')}}" style="font-family: 'Oswald', sans-serif;">| Create Your Blog |</a></h4>
         {% endif%}
        </div>
         
      </div>
<div class="container-fluid">
  <div class="row" style="font-family: 'Oswald', sans-serif;">
    {{macro.displayBlogs(blogs)}}
  </div>
</div>
{%endblock%}

blog/templates/sports.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="container-fluid">
<div class="jumbotron text-center mdb-color lighten-2 white-text mx-2 mb-5">

        
        <h2 class="card-title h2" style="font-family: 'Oswald', sans-serif;">Only the best and most popular Sports blogs</h2>      
      
        <hr class="my-4 rgba-white-light">   
      
      </div>
    
      <div class="row">
          <div class="col-md-5"></div>
          <div class="col-md-6">
         {% if current_user.is_authenticated %}
          <h4 class="text-center btn bg-light mb-3"><a href="{{url_for('main.new_blog')}}" style="font-family: 'Oswald', sans-serif;">| Create Your Blog |</a></h4>
         {% endif%}
        </div>
         
      </div>
    </div>
<div class="container-fluid">
  <div class="row" style="font-family: 'Oswald', sans-serif;">
    {{macro.displayBlogs(blogs)}}
  </div>
</div>
{%endblock%}